# Header
menu:
  主页: /
  所有文章: /archives
  #书单: /2016/09/08/书单/

# SubNav
subnav:
  github: "https://github.com/fdx321"
  weibo: "http://weibo.com/fdx321"
  #rss: "#"
  zhihu: "http://www.zhihu.com/people/xie-xi-ming"
  #douban: "#"
  mail: "mailto:fdx321@126.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: true

# Miscellaneous
google_analytics: true
favicon: /favicon.png

#你的头像url
#avatar: http://wx2.sinaimg.cn/small/6a2787d4ly8fn9hdgyfsbj20dc0dc0uo.jpg
avatar: https://wx1.sinaimg.cn/mw690/6a2787d4gy1fthip0widbj20pu0pw43p.jpg
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  虎扑篮球: http://nba.hupu.com/
  伯乐在线: http://blog.jobbole.com/
  ImportNew: http://www.importnew.com/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 某互联网金融公司资浅工程师.
